create table quiz_questions
(
    id             int auto_increment
        primary key,
    category       varchar(255)                          not null,
    question       text                                  not null,
    option_a       text                                  not null,
    option_b       text                                  not null,
    option_c       text                                  not null,
    option_d       text                                  not null,
    correct_option char                                  not null,
    created_at     timestamp default current_timestamp() not null
);

INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('basic', 'Dlaczego cyberbezpieczeństwo jest ważne?', 'Chroni przed zagrożeniami fizycznymi', 'Zapewnia ochronę danych i systemów komputerowych', 'Eliminuje potrzebę stosowania haseł', 'Gwarantuje brak wirusów w Internecie', 'b', '2025-01-03 17:58:18');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('basic', 'Co to jest malware?', 'Rodzaj bezpiecznego oprogramowania', 'Oprogramowanie szpiegujące lub uszkadzające dane', 'System operacyjny', 'Metoda szyfrowania danych', 'b', '2025-01-03 17:58:18');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('basic', 'Jakie są podstawowe zasady ochrony danych osobowych?', 'Używanie jednolitego hasła do wszystkich kont', 'Udostępnianie danych osobowych na żądanie', 'Minimalizacja danych, regularne aktualizacje', 'Przechowywanie danych wyłącznie na dyskach zewnętrznych', 'c', '2025-01-03 17:58:18');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('basic', 'Jakie są zasady tworzenia silnych haseł?', 'Hasło powinno być krótkie i proste', 'Hasło powinno zawierać kombinację liter, cyfr i znaków specjalnych', 'Hasło powinno być imieniem użytkownika', 'Hasło powinno być takie same jak PIN karty', 'b', '2025-01-03 17:58:18');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('basic', 'Co oznacza termin phishing?', 'Ochrona przed wirusami', 'Wyłudzanie danych osobowych za pomocą fałszywych wiadomości', 'Szyfrowanie danych', 'Atak na serwery', 'b', '2025-01-03 17:58:18');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('basic', 'Jak zabezpieczyć urządzenia mobilne?', 'Instalować aplikacje tylko z oficjalnych sklepów', 'Wyłączyć wszystkie aktualizacje', 'Korzystać z darmowych sieci Wi-Fi bez zabezpieczeń', 'Nie używać haseł do blokady ekranu', 'a', '2025-01-03 17:58:18');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('basic', 'Czym jest ransomware?', 'Rodzaj aplikacji do zarządzania danymi', 'Oprogramowanie blokujące dostęp do danych i żądające okupu', 'Program antywirusowy', 'Metoda ochrony sieci', 'b', '2025-01-03 17:58:18');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('basic', 'Jak rozpoznać bezpieczną stronę internetową?', 'Adres zaczyna się od "http://"', 'Adres zaczyna się od "https://" i posiada certyfikat SSL', 'Strona ma kolorowe tło', 'Strona nie wymaga logowania', 'b', '2025-01-03 17:58:18');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('basic', 'Dlaczego aktualizacje oprogramowania są ważne?', 'Dodają nowe funkcje do programów', 'Usuwają znane luki w zabezpieczeniach', 'Zmniejszają wydajność systemu', 'Sprawiają, że system jest mniej stabilny', 'b', '2025-01-03 17:58:18');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('basic', 'Co oznacza pojęcie "zapora ogniowa"?', 'Fizyczna blokada urządzenia', 'Oprogramowanie lub urządzenie filtrujące ruch sieciowy', 'Program do odzyskiwania danych', 'Narzędzie do kompresji plików', 'b', '2025-01-03 17:58:18');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('medium', 'Czym jest atak DDoS?', 'Jednorazowe usunięcie plików z serwera', 'Przeciążenie serwera za pomocą ogromnej liczby zapytań', 'Bezpośredni atak na użytkownika', 'Sposób na przyspieszenie działania sieci', 'b', '2025-01-03 18:01:09');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('medium', 'Jakie są podstawowe elementy zarządzania ryzykiem?', 'Identyfikacja zagrożeń, ocena ryzyka, wdrożenie środków zaradczych', 'Kopiowanie danych na dyski zewnętrzne', 'Blokowanie dostępu do Internetu', 'Usuwanie starych plików', 'a', '2025-01-03 18:01:09');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('medium', 'Czym charakteryzuje się atak Man-in-the-Middle?', 'Atakujący podszywa się pod użytkownika w rozmowie', 'Zaatakowanie serwera hostingowego', 'Bezpośredni atak na system operacyjny', 'Szyfrowanie wiadomości email', 'a', '2025-01-03 18:01:09');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('medium', 'Co oznacza skrót GDPR?', 'General Data Protection Regulation', 'General Development Program Rules', 'Global Data Policy Regulations', 'Governmental Data Protection Requirements', 'a', '2025-01-03 18:01:09');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('medium', 'Jak można zabezpieczać sieci wewnętrzne?', 'Wyłączanie zapory ogniowej', 'Używanie VPN i segmentacja sieci', 'Zablokowanie dostępu do wszystkich stron internetowych', 'Instalacja oprogramowania do udostępniania plików', 'b', '2025-01-03 18:01:09');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('medium', 'Jakie są podstawowe zasady bezpieczeństwa w pracy zdalnej?', 'Używanie publicznych sieci Wi-Fi', 'Korzystanie z VPN oraz aktualizowanego oprogramowania', 'Udostępnianie haseł współpracownikom', 'Wyłączanie antywirusa na czas pracy', 'b', '2025-01-03 18:01:09');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('medium', 'Co to jest segmentacja sieci?', 'Podział sieci na mniejsze części w celu zwiększenia bezpieczeństwa', 'Proces usuwania danych z sieci', 'Tworzenie kopii zapasowych', 'Wyłączenie dostępu do Internetu', 'a', '2025-01-03 18:01:09');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('medium', 'Czym charakteryzuje się polityka "Zero Trust"?', 'Automatyczne akceptowanie dostępu do sieci', 'Zasada minimalnych uprawnień i weryfikacji każdego żądania', 'Brak zabezpieczeń w systemach', 'Swobodne udostępnianie danych', 'b', '2025-01-03 18:01:09');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('medium', 'Jakie są konsekwencje niezgodności z GDPR?', 'Kara finansowa i utrata reputacji', 'Utrata danych osobowych', 'Blokada dostępu do Internetu', 'Przymus zmiany oprogramowania', 'a', '2025-01-03 18:01:09');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('medium', 'Jak działa IDS (Intrusion Detection System)?', 'Blokuje podejrzany ruch sieciowy', 'Monitoruje sieć i identyfikuje potencjalne zagrożenia', 'Tworzy kopie zapasowe danych', 'Przyspiesza działanie aplikacji', 'b', '2025-01-03 18:01:09');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('advanced', 'Co to jest exploit development?', 'Proces wykrywania luk w oprogramowaniu i ich wykorzystania', 'Tworzenie bezpiecznych aplikacji', 'Ochrona danych osobowych', 'Skanowanie sieci w poszukiwaniu zagrożeń', 'a', '2025-01-03 18:07:57');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('advanced', 'Jakie narzędzia służą do analizy zagrożeń?', 'Wireshark, Snort, Splunk', 'Excel i Word', 'Przeglądarki internetowe', 'Programy do tworzenia kopii zapasowych', 'a', '2025-01-03 18:07:57');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('advanced', 'Jakie są kluczowe kroki w reagowaniu na incydenty?', 'Ignorowanie zgłoszenia, aby nie wywoływać paniki', 'Identyfikacja, izolacja, analiza, usunięcie zagrożenia', 'Automatyczne usunięcie wszystkich plików', 'Zrestartowanie wszystkich urządzeń', 'b', '2025-01-03 18:07:57');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('advanced', 'Jak zabezpieczać aplikacje webowe?', 'Regularne aktualizacje i stosowanie mechanizmów uwierzytelniania', 'Usunięcie wszystkich zabezpieczeń', 'Przechowywanie danych w formacie niezaszyfrowanym', 'Wyłączenie logowania użytkowników', 'a', '2025-01-03 18:07:57');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('advanced', 'Co oznacza termin inżynieria wsteczna?', 'Tworzenie oprogramowania od podstaw', 'Analiza istniejącego oprogramowania w celu poznania jego struktury i działania', 'Kopiowanie plików z jednego systemu na drugi', 'Szyfrowanie danych', 'b', '2025-01-03 18:07:57');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('advanced', 'Jakie są zagrożenia związane z oprogramowaniem open-source?', 'Brak możliwości jego modyfikacji', 'Potencjalne luki w zabezpieczeniach z powodu publicznego dostępu do kodu', 'Brak kosztów licencji', 'Gwarancja braku zagrożeń', 'b', '2025-01-03 18:07:57');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('advanced', 'Jak działa SIEM (Security Information and Event Management)?', 'Monitoruje i analizuje zdarzenia bezpieczeństwa w czasie rzeczywistym', 'Tworzy kopie zapasowe danych', 'Optymalizuje działanie aplikacji', 'Wyłącza podejrzane urządzenia', 'a', '2025-01-03 18:07:57');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('advanced', 'Jakie są techniki obrony przed inżynierią wsteczną?', 'Szyfrowanie kodu i stosowanie obfuskacji', 'Publiczne udostępnienie kodu źródłowego', 'Automatyczne generowanie dokumentacji', 'Brak zabezpieczeń w oprogramowaniu', 'a', '2025-01-03 18:07:57');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('advanced', 'Co oznacza termin "threat hunting"?', 'Aktywne wyszukiwanie zagrożeń w systemie', 'Tworzenie kopii zapasowych danych', 'Blokowanie wszystkich połączeń sieciowych', 'Automatyczne aktualizacje oprogramowania', 'a', '2025-01-03 18:07:57');
INSERT INTO quizz.quiz_questions (category, question, option_a, option_b, option_c, option_d, correct_option, created_at) VALUES ('advanced', 'Jakie są zalety stosowania izolowanych środowisk testowych (sandbox)?', 'Umożliwiają bezpieczne testowanie oprogramowania', 'Przyspieszają działanie systemu operacyjnego', 'Blokują wszystkie połączenia internetowe', 'Zmniejszają koszty licencji', 'a', '2025-01-03 18:07:57');
